import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from "../../environments/environment";
import { Cartelera, InfoMovie, SearchMovie } from "../models/movie";
import { URI } from 'src/constant/api';


const api_key = environment.API_KEY_V3
const languaje = "es-ES"
@Injectable({
  providedIn: 'root'
})
export class MovieService {

  constructor(private http: HttpClient) {
  }


  getCartelera(page = 1): Observable<Cartelera> {
    const params = { api_key, languaje, page: page.toString(), language: "es" }
    return this.http
      .get<Cartelera>(`${URI}/movie/now_playing`, { params })
  }
  search(query: string, page = 1) {
    const params = { api_key, languaje, page: page.toString(), query, language: "es" }
    console.log({ params })
    return this.http.get<SearchMovie>(`${URI}/search/movie`, { params })
  }
  byId(id: number) {
    const params = { api_key, languaje, language: "es" }
    return this.http.get<InfoMovie>(`${URI}/movie/${id}`, { params })
  }
}
// Generated by https://quicktype.io
